/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.ClientHealthResponseScoreDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ClientHealthResponseResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class ClientHealthResponseResponse {
  @SerializedName("siteId")
  private String siteId = null;

  @SerializedName("scoreDetail")
  private List<ClientHealthResponseScoreDetail> scoreDetail = null;

  public ClientHealthResponseResponse siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public ClientHealthResponseResponse scoreDetail(List<ClientHealthResponseScoreDetail> scoreDetail) {
    this.scoreDetail = scoreDetail;
    return this;
  }

  public ClientHealthResponseResponse addScoreDetailItem(ClientHealthResponseScoreDetail scoreDetailItem) {
    if (this.scoreDetail == null) {
      this.scoreDetail = new ArrayList<>();
    }
    this.scoreDetail.add(scoreDetailItem);
    return this;
  }

   /**
   * Get scoreDetail
   * @return scoreDetail
  **/
  @ApiModelProperty(value = "")
  public List<ClientHealthResponseScoreDetail> getScoreDetail() {
    return scoreDetail;
  }

  public void setScoreDetail(List<ClientHealthResponseScoreDetail> scoreDetail) {
    this.scoreDetail = scoreDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientHealthResponseResponse clientHealthResponseResponse = (ClientHealthResponseResponse) o;
    return Objects.equals(this.siteId, clientHealthResponseResponse.siteId) &&
        Objects.equals(this.scoreDetail, clientHealthResponseResponse.scoreDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(siteId, scoreDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientHealthResponseResponse {\n");
    
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    scoreDetail: ").append(toIndentedString(scoreDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

