/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeleteSSIDResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class DeleteSSIDResponse {
  @SerializedName("isError")
  private Boolean isError = null;

  @SerializedName("failureReason")
  private String failureReason = null;

  @SerializedName("successMessage")
  private String successMessage = null;

  public DeleteSSIDResponse isError(Boolean isError) {
    this.isError = isError;
    return this;
  }

   /**
   * Get isError
   * @return isError
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsError() {
    return isError;
  }

  public void setIsError(Boolean isError) {
    this.isError = isError;
  }

  public DeleteSSIDResponse failureReason(String failureReason) {
    this.failureReason = failureReason;
    return this;
  }

   /**
   * Get failureReason
   * @return failureReason
  **/
  @ApiModelProperty(value = "")
  public String getFailureReason() {
    return failureReason;
  }

  public void setFailureReason(String failureReason) {
    this.failureReason = failureReason;
  }

  public DeleteSSIDResponse successMessage(String successMessage) {
    this.successMessage = successMessage;
    return this;
  }

   /**
   * Get successMessage
   * @return successMessage
  **/
  @ApiModelProperty(value = "")
  public String getSuccessMessage() {
    return successMessage;
  }

  public void setSuccessMessage(String successMessage) {
    this.successMessage = successMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteSSIDResponse deleteSSIDResponse = (DeleteSSIDResponse) o;
    return Objects.equals(this.isError, deleteSSIDResponse.isError) &&
        Objects.equals(this.failureReason, deleteSSIDResponse.failureReason) &&
        Objects.equals(this.successMessage, deleteSSIDResponse.successMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isError, failureReason, successMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteSSIDResponse {\n");
    
    sb.append("    isError: ").append(toIndentedString(isError)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("    successMessage: ").append(toIndentedString(successMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

