/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeviceInnerDeviceInfoIpInterfaces
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class DeviceInnerDeviceInfoIpInterfaces {
  @SerializedName("ipv4Address")
  private Object ipv4Address = null;

  @SerializedName("ipv6AddressList")
  private List<Object> ipv6AddressList = null;

  @SerializedName("macAddress")
  private String macAddress = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  public DeviceInnerDeviceInfoIpInterfaces ipv4Address(Object ipv4Address) {
    this.ipv4Address = ipv4Address;
    return this;
  }

   /**
   * Get ipv4Address
   * @return ipv4Address
  **/
  @ApiModelProperty(value = "")
  public Object getIpv4Address() {
    return ipv4Address;
  }

  public void setIpv4Address(Object ipv4Address) {
    this.ipv4Address = ipv4Address;
  }

  public DeviceInnerDeviceInfoIpInterfaces ipv6AddressList(List<Object> ipv6AddressList) {
    this.ipv6AddressList = ipv6AddressList;
    return this;
  }

  public DeviceInnerDeviceInfoIpInterfaces addIpv6AddressListItem(Object ipv6AddressListItem) {
    if (this.ipv6AddressList == null) {
      this.ipv6AddressList = new ArrayList<>();
    }
    this.ipv6AddressList.add(ipv6AddressListItem);
    return this;
  }

   /**
   * Get ipv6AddressList
   * @return ipv6AddressList
  **/
  @ApiModelProperty(value = "")
  public List<Object> getIpv6AddressList() {
    return ipv6AddressList;
  }

  public void setIpv6AddressList(List<Object> ipv6AddressList) {
    this.ipv6AddressList = ipv6AddressList;
  }

  public DeviceInnerDeviceInfoIpInterfaces macAddress(String macAddress) {
    this.macAddress = macAddress;
    return this;
  }

   /**
   * Get macAddress
   * @return macAddress
  **/
  @ApiModelProperty(value = "")
  public String getMacAddress() {
    return macAddress;
  }

  public void setMacAddress(String macAddress) {
    this.macAddress = macAddress;
  }

  public DeviceInnerDeviceInfoIpInterfaces name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeviceInnerDeviceInfoIpInterfaces status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceInnerDeviceInfoIpInterfaces deviceInnerDeviceInfoIpInterfaces = (DeviceInnerDeviceInfoIpInterfaces) o;
    return Objects.equals(this.ipv4Address, deviceInnerDeviceInfoIpInterfaces.ipv4Address) &&
        Objects.equals(this.ipv6AddressList, deviceInnerDeviceInfoIpInterfaces.ipv6AddressList) &&
        Objects.equals(this.macAddress, deviceInnerDeviceInfoIpInterfaces.macAddress) &&
        Objects.equals(this.name, deviceInnerDeviceInfoIpInterfaces.name) &&
        Objects.equals(this.status, deviceInnerDeviceInfoIpInterfaces.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipv4Address, ipv6AddressList, macAddress, name, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceInnerDeviceInfoIpInterfaces {\n");
    
    sb.append("    ipv4Address: ").append(toIndentedString(ipv4Address)).append("\n");
    sb.append("    ipv6AddressList: ").append(toIndentedString(ipv6AddressList)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

