/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.HTTPReadCredentialDTOInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DiscoveryNIO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class DiscoveryNIO {
  @SerializedName("attributeInfo")
  private Object attributeInfo = null;

  @SerializedName("cdpLevel")
  private Integer cdpLevel = null;

  @SerializedName("deviceIds")
  private String deviceIds = null;

  @SerializedName("discoveryCondition")
  private String discoveryCondition = null;

  @SerializedName("discoveryStatus")
  private String discoveryStatus = null;

  @SerializedName("discoveryType")
  private String discoveryType = null;

  @SerializedName("enablePasswordList")
  private String enablePasswordList = null;

  @SerializedName("globalCredentialIdList")
  private List<String> globalCredentialIdList = null;

  @SerializedName("httpReadCredential")
  private HTTPReadCredentialDTOInner httpReadCredential = null;

  @SerializedName("httpWriteCredential")
  private HTTPReadCredentialDTOInner httpWriteCredential = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("ipAddressList")
  private String ipAddressList = null;

  @SerializedName("ipFilterList")
  private String ipFilterList = null;

  @SerializedName("isAutoCdp")
  private Boolean isAutoCdp = null;

  @SerializedName("lldpLevel")
  private Integer lldpLevel = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("netconfPort")
  private String netconfPort = null;

  @SerializedName("numDevices")
  private Integer numDevices = null;

  @SerializedName("parentDiscoveryId")
  private String parentDiscoveryId = null;

  @SerializedName("passwordList")
  private String passwordList = null;

  @SerializedName("preferredMgmtIPMethod")
  private String preferredMgmtIPMethod = null;

  @SerializedName("protocolOrder")
  private String protocolOrder = null;

  @SerializedName("retryCount")
  private Integer retryCount = null;

  @SerializedName("snmpAuthPassphrase")
  private String snmpAuthPassphrase = null;

  @SerializedName("snmpAuthProtocol")
  private String snmpAuthProtocol = null;

  @SerializedName("snmpMode")
  private String snmpMode = null;

  @SerializedName("snmpPrivPassphrase")
  private String snmpPrivPassphrase = null;

  @SerializedName("snmpPrivProtocol")
  private String snmpPrivProtocol = null;

  @SerializedName("snmpRoCommunity")
  private String snmpRoCommunity = null;

  @SerializedName("snmpRoCommunityDesc")
  private String snmpRoCommunityDesc = null;

  @SerializedName("snmpRwCommunity")
  private String snmpRwCommunity = null;

  @SerializedName("snmpRwCommunityDesc")
  private String snmpRwCommunityDesc = null;

  @SerializedName("snmpUserName")
  private String snmpUserName = null;

  @SerializedName("timeOut")
  private Integer timeOut = null;

  @SerializedName("updateMgmtIp")
  private Boolean updateMgmtIp = null;

  @SerializedName("userNameList")
  private String userNameList = null;

  public DiscoveryNIO attributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
    return this;
  }

   /**
   * Get attributeInfo
   * @return attributeInfo
  **/
  @ApiModelProperty(value = "")
  public Object getAttributeInfo() {
    return attributeInfo;
  }

  public void setAttributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
  }

  public DiscoveryNIO cdpLevel(Integer cdpLevel) {
    this.cdpLevel = cdpLevel;
    return this;
  }

   /**
   * Get cdpLevel
   * @return cdpLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getCdpLevel() {
    return cdpLevel;
  }

  public void setCdpLevel(Integer cdpLevel) {
    this.cdpLevel = cdpLevel;
  }

  public DiscoveryNIO deviceIds(String deviceIds) {
    this.deviceIds = deviceIds;
    return this;
  }

   /**
   * Get deviceIds
   * @return deviceIds
  **/
  @ApiModelProperty(value = "")
  public String getDeviceIds() {
    return deviceIds;
  }

  public void setDeviceIds(String deviceIds) {
    this.deviceIds = deviceIds;
  }

  public DiscoveryNIO discoveryCondition(String discoveryCondition) {
    this.discoveryCondition = discoveryCondition;
    return this;
  }

   /**
   * Get discoveryCondition
   * @return discoveryCondition
  **/
  @ApiModelProperty(value = "")
  public String getDiscoveryCondition() {
    return discoveryCondition;
  }

  public void setDiscoveryCondition(String discoveryCondition) {
    this.discoveryCondition = discoveryCondition;
  }

  public DiscoveryNIO discoveryStatus(String discoveryStatus) {
    this.discoveryStatus = discoveryStatus;
    return this;
  }

   /**
   * Get discoveryStatus
   * @return discoveryStatus
  **/
  @ApiModelProperty(value = "")
  public String getDiscoveryStatus() {
    return discoveryStatus;
  }

  public void setDiscoveryStatus(String discoveryStatus) {
    this.discoveryStatus = discoveryStatus;
  }

  public DiscoveryNIO discoveryType(String discoveryType) {
    this.discoveryType = discoveryType;
    return this;
  }

   /**
   * Get discoveryType
   * @return discoveryType
  **/
  @ApiModelProperty(value = "")
  public String getDiscoveryType() {
    return discoveryType;
  }

  public void setDiscoveryType(String discoveryType) {
    this.discoveryType = discoveryType;
  }

  public DiscoveryNIO enablePasswordList(String enablePasswordList) {
    this.enablePasswordList = enablePasswordList;
    return this;
  }

   /**
   * Get enablePasswordList
   * @return enablePasswordList
  **/
  @ApiModelProperty(value = "")
  public String getEnablePasswordList() {
    return enablePasswordList;
  }

  public void setEnablePasswordList(String enablePasswordList) {
    this.enablePasswordList = enablePasswordList;
  }

  public DiscoveryNIO globalCredentialIdList(List<String> globalCredentialIdList) {
    this.globalCredentialIdList = globalCredentialIdList;
    return this;
  }

  public DiscoveryNIO addGlobalCredentialIdListItem(String globalCredentialIdListItem) {
    if (this.globalCredentialIdList == null) {
      this.globalCredentialIdList = new ArrayList<>();
    }
    this.globalCredentialIdList.add(globalCredentialIdListItem);
    return this;
  }

   /**
   * Get globalCredentialIdList
   * @return globalCredentialIdList
  **/
  @ApiModelProperty(value = "")
  public List<String> getGlobalCredentialIdList() {
    return globalCredentialIdList;
  }

  public void setGlobalCredentialIdList(List<String> globalCredentialIdList) {
    this.globalCredentialIdList = globalCredentialIdList;
  }

  public DiscoveryNIO httpReadCredential(HTTPReadCredentialDTOInner httpReadCredential) {
    this.httpReadCredential = httpReadCredential;
    return this;
  }

   /**
   * Get httpReadCredential
   * @return httpReadCredential
  **/
  @ApiModelProperty(value = "")
  public HTTPReadCredentialDTOInner getHttpReadCredential() {
    return httpReadCredential;
  }

  public void setHttpReadCredential(HTTPReadCredentialDTOInner httpReadCredential) {
    this.httpReadCredential = httpReadCredential;
  }

  public DiscoveryNIO httpWriteCredential(HTTPReadCredentialDTOInner httpWriteCredential) {
    this.httpWriteCredential = httpWriteCredential;
    return this;
  }

   /**
   * Get httpWriteCredential
   * @return httpWriteCredential
  **/
  @ApiModelProperty(value = "")
  public HTTPReadCredentialDTOInner getHttpWriteCredential() {
    return httpWriteCredential;
  }

  public void setHttpWriteCredential(HTTPReadCredentialDTOInner httpWriteCredential) {
    this.httpWriteCredential = httpWriteCredential;
  }

  public DiscoveryNIO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DiscoveryNIO ipAddressList(String ipAddressList) {
    this.ipAddressList = ipAddressList;
    return this;
  }

   /**
   * Get ipAddressList
   * @return ipAddressList
  **/
  @ApiModelProperty(value = "")
  public String getIpAddressList() {
    return ipAddressList;
  }

  public void setIpAddressList(String ipAddressList) {
    this.ipAddressList = ipAddressList;
  }

  public DiscoveryNIO ipFilterList(String ipFilterList) {
    this.ipFilterList = ipFilterList;
    return this;
  }

   /**
   * Get ipFilterList
   * @return ipFilterList
  **/
  @ApiModelProperty(value = "")
  public String getIpFilterList() {
    return ipFilterList;
  }

  public void setIpFilterList(String ipFilterList) {
    this.ipFilterList = ipFilterList;
  }

  public DiscoveryNIO isAutoCdp(Boolean isAutoCdp) {
    this.isAutoCdp = isAutoCdp;
    return this;
  }

   /**
   * Get isAutoCdp
   * @return isAutoCdp
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsAutoCdp() {
    return isAutoCdp;
  }

  public void setIsAutoCdp(Boolean isAutoCdp) {
    this.isAutoCdp = isAutoCdp;
  }

  public DiscoveryNIO lldpLevel(Integer lldpLevel) {
    this.lldpLevel = lldpLevel;
    return this;
  }

   /**
   * Get lldpLevel
   * @return lldpLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getLldpLevel() {
    return lldpLevel;
  }

  public void setLldpLevel(Integer lldpLevel) {
    this.lldpLevel = lldpLevel;
  }

  public DiscoveryNIO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DiscoveryNIO netconfPort(String netconfPort) {
    this.netconfPort = netconfPort;
    return this;
  }

   /**
   * Get netconfPort
   * @return netconfPort
  **/
  @ApiModelProperty(value = "")
  public String getNetconfPort() {
    return netconfPort;
  }

  public void setNetconfPort(String netconfPort) {
    this.netconfPort = netconfPort;
  }

  public DiscoveryNIO numDevices(Integer numDevices) {
    this.numDevices = numDevices;
    return this;
  }

   /**
   * Get numDevices
   * @return numDevices
  **/
  @ApiModelProperty(value = "")
  public Integer getNumDevices() {
    return numDevices;
  }

  public void setNumDevices(Integer numDevices) {
    this.numDevices = numDevices;
  }

  public DiscoveryNIO parentDiscoveryId(String parentDiscoveryId) {
    this.parentDiscoveryId = parentDiscoveryId;
    return this;
  }

   /**
   * Get parentDiscoveryId
   * @return parentDiscoveryId
  **/
  @ApiModelProperty(value = "")
  public String getParentDiscoveryId() {
    return parentDiscoveryId;
  }

  public void setParentDiscoveryId(String parentDiscoveryId) {
    this.parentDiscoveryId = parentDiscoveryId;
  }

  public DiscoveryNIO passwordList(String passwordList) {
    this.passwordList = passwordList;
    return this;
  }

   /**
   * Get passwordList
   * @return passwordList
  **/
  @ApiModelProperty(value = "")
  public String getPasswordList() {
    return passwordList;
  }

  public void setPasswordList(String passwordList) {
    this.passwordList = passwordList;
  }

  public DiscoveryNIO preferredMgmtIPMethod(String preferredMgmtIPMethod) {
    this.preferredMgmtIPMethod = preferredMgmtIPMethod;
    return this;
  }

   /**
   * Get preferredMgmtIPMethod
   * @return preferredMgmtIPMethod
  **/
  @ApiModelProperty(value = "")
  public String getPreferredMgmtIPMethod() {
    return preferredMgmtIPMethod;
  }

  public void setPreferredMgmtIPMethod(String preferredMgmtIPMethod) {
    this.preferredMgmtIPMethod = preferredMgmtIPMethod;
  }

  public DiscoveryNIO protocolOrder(String protocolOrder) {
    this.protocolOrder = protocolOrder;
    return this;
  }

   /**
   * Get protocolOrder
   * @return protocolOrder
  **/
  @ApiModelProperty(value = "")
  public String getProtocolOrder() {
    return protocolOrder;
  }

  public void setProtocolOrder(String protocolOrder) {
    this.protocolOrder = protocolOrder;
  }

  public DiscoveryNIO retryCount(Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

   /**
   * Get retryCount
   * @return retryCount
  **/
  @ApiModelProperty(value = "")
  public Integer getRetryCount() {
    return retryCount;
  }

  public void setRetryCount(Integer retryCount) {
    this.retryCount = retryCount;
  }

  public DiscoveryNIO snmpAuthPassphrase(String snmpAuthPassphrase) {
    this.snmpAuthPassphrase = snmpAuthPassphrase;
    return this;
  }

   /**
   * Get snmpAuthPassphrase
   * @return snmpAuthPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getSnmpAuthPassphrase() {
    return snmpAuthPassphrase;
  }

  public void setSnmpAuthPassphrase(String snmpAuthPassphrase) {
    this.snmpAuthPassphrase = snmpAuthPassphrase;
  }

  public DiscoveryNIO snmpAuthProtocol(String snmpAuthProtocol) {
    this.snmpAuthProtocol = snmpAuthProtocol;
    return this;
  }

   /**
   * Get snmpAuthProtocol
   * @return snmpAuthProtocol
  **/
  @ApiModelProperty(value = "")
  public String getSnmpAuthProtocol() {
    return snmpAuthProtocol;
  }

  public void setSnmpAuthProtocol(String snmpAuthProtocol) {
    this.snmpAuthProtocol = snmpAuthProtocol;
  }

  public DiscoveryNIO snmpMode(String snmpMode) {
    this.snmpMode = snmpMode;
    return this;
  }

   /**
   * Get snmpMode
   * @return snmpMode
  **/
  @ApiModelProperty(value = "")
  public String getSnmpMode() {
    return snmpMode;
  }

  public void setSnmpMode(String snmpMode) {
    this.snmpMode = snmpMode;
  }

  public DiscoveryNIO snmpPrivPassphrase(String snmpPrivPassphrase) {
    this.snmpPrivPassphrase = snmpPrivPassphrase;
    return this;
  }

   /**
   * Get snmpPrivPassphrase
   * @return snmpPrivPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getSnmpPrivPassphrase() {
    return snmpPrivPassphrase;
  }

  public void setSnmpPrivPassphrase(String snmpPrivPassphrase) {
    this.snmpPrivPassphrase = snmpPrivPassphrase;
  }

  public DiscoveryNIO snmpPrivProtocol(String snmpPrivProtocol) {
    this.snmpPrivProtocol = snmpPrivProtocol;
    return this;
  }

   /**
   * Get snmpPrivProtocol
   * @return snmpPrivProtocol
  **/
  @ApiModelProperty(value = "")
  public String getSnmpPrivProtocol() {
    return snmpPrivProtocol;
  }

  public void setSnmpPrivProtocol(String snmpPrivProtocol) {
    this.snmpPrivProtocol = snmpPrivProtocol;
  }

  public DiscoveryNIO snmpRoCommunity(String snmpRoCommunity) {
    this.snmpRoCommunity = snmpRoCommunity;
    return this;
  }

   /**
   * Get snmpRoCommunity
   * @return snmpRoCommunity
  **/
  @ApiModelProperty(value = "")
  public String getSnmpRoCommunity() {
    return snmpRoCommunity;
  }

  public void setSnmpRoCommunity(String snmpRoCommunity) {
    this.snmpRoCommunity = snmpRoCommunity;
  }

  public DiscoveryNIO snmpRoCommunityDesc(String snmpRoCommunityDesc) {
    this.snmpRoCommunityDesc = snmpRoCommunityDesc;
    return this;
  }

   /**
   * Get snmpRoCommunityDesc
   * @return snmpRoCommunityDesc
  **/
  @ApiModelProperty(value = "")
  public String getSnmpRoCommunityDesc() {
    return snmpRoCommunityDesc;
  }

  public void setSnmpRoCommunityDesc(String snmpRoCommunityDesc) {
    this.snmpRoCommunityDesc = snmpRoCommunityDesc;
  }

  public DiscoveryNIO snmpRwCommunity(String snmpRwCommunity) {
    this.snmpRwCommunity = snmpRwCommunity;
    return this;
  }

   /**
   * Get snmpRwCommunity
   * @return snmpRwCommunity
  **/
  @ApiModelProperty(value = "")
  public String getSnmpRwCommunity() {
    return snmpRwCommunity;
  }

  public void setSnmpRwCommunity(String snmpRwCommunity) {
    this.snmpRwCommunity = snmpRwCommunity;
  }

  public DiscoveryNIO snmpRwCommunityDesc(String snmpRwCommunityDesc) {
    this.snmpRwCommunityDesc = snmpRwCommunityDesc;
    return this;
  }

   /**
   * Get snmpRwCommunityDesc
   * @return snmpRwCommunityDesc
  **/
  @ApiModelProperty(value = "")
  public String getSnmpRwCommunityDesc() {
    return snmpRwCommunityDesc;
  }

  public void setSnmpRwCommunityDesc(String snmpRwCommunityDesc) {
    this.snmpRwCommunityDesc = snmpRwCommunityDesc;
  }

  public DiscoveryNIO snmpUserName(String snmpUserName) {
    this.snmpUserName = snmpUserName;
    return this;
  }

   /**
   * Get snmpUserName
   * @return snmpUserName
  **/
  @ApiModelProperty(value = "")
  public String getSnmpUserName() {
    return snmpUserName;
  }

  public void setSnmpUserName(String snmpUserName) {
    this.snmpUserName = snmpUserName;
  }

  public DiscoveryNIO timeOut(Integer timeOut) {
    this.timeOut = timeOut;
    return this;
  }

   /**
   * Get timeOut
   * @return timeOut
  **/
  @ApiModelProperty(value = "")
  public Integer getTimeOut() {
    return timeOut;
  }

  public void setTimeOut(Integer timeOut) {
    this.timeOut = timeOut;
  }

  public DiscoveryNIO updateMgmtIp(Boolean updateMgmtIp) {
    this.updateMgmtIp = updateMgmtIp;
    return this;
  }

   /**
   * Get updateMgmtIp
   * @return updateMgmtIp
  **/
  @ApiModelProperty(value = "")
  public Boolean isUpdateMgmtIp() {
    return updateMgmtIp;
  }

  public void setUpdateMgmtIp(Boolean updateMgmtIp) {
    this.updateMgmtIp = updateMgmtIp;
  }

  public DiscoveryNIO userNameList(String userNameList) {
    this.userNameList = userNameList;
    return this;
  }

   /**
   * Get userNameList
   * @return userNameList
  **/
  @ApiModelProperty(value = "")
  public String getUserNameList() {
    return userNameList;
  }

  public void setUserNameList(String userNameList) {
    this.userNameList = userNameList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscoveryNIO discoveryNIO = (DiscoveryNIO) o;
    return Objects.equals(this.attributeInfo, discoveryNIO.attributeInfo) &&
        Objects.equals(this.cdpLevel, discoveryNIO.cdpLevel) &&
        Objects.equals(this.deviceIds, discoveryNIO.deviceIds) &&
        Objects.equals(this.discoveryCondition, discoveryNIO.discoveryCondition) &&
        Objects.equals(this.discoveryStatus, discoveryNIO.discoveryStatus) &&
        Objects.equals(this.discoveryType, discoveryNIO.discoveryType) &&
        Objects.equals(this.enablePasswordList, discoveryNIO.enablePasswordList) &&
        Objects.equals(this.globalCredentialIdList, discoveryNIO.globalCredentialIdList) &&
        Objects.equals(this.httpReadCredential, discoveryNIO.httpReadCredential) &&
        Objects.equals(this.httpWriteCredential, discoveryNIO.httpWriteCredential) &&
        Objects.equals(this.id, discoveryNIO.id) &&
        Objects.equals(this.ipAddressList, discoveryNIO.ipAddressList) &&
        Objects.equals(this.ipFilterList, discoveryNIO.ipFilterList) &&
        Objects.equals(this.isAutoCdp, discoveryNIO.isAutoCdp) &&
        Objects.equals(this.lldpLevel, discoveryNIO.lldpLevel) &&
        Objects.equals(this.name, discoveryNIO.name) &&
        Objects.equals(this.netconfPort, discoveryNIO.netconfPort) &&
        Objects.equals(this.numDevices, discoveryNIO.numDevices) &&
        Objects.equals(this.parentDiscoveryId, discoveryNIO.parentDiscoveryId) &&
        Objects.equals(this.passwordList, discoveryNIO.passwordList) &&
        Objects.equals(this.preferredMgmtIPMethod, discoveryNIO.preferredMgmtIPMethod) &&
        Objects.equals(this.protocolOrder, discoveryNIO.protocolOrder) &&
        Objects.equals(this.retryCount, discoveryNIO.retryCount) &&
        Objects.equals(this.snmpAuthPassphrase, discoveryNIO.snmpAuthPassphrase) &&
        Objects.equals(this.snmpAuthProtocol, discoveryNIO.snmpAuthProtocol) &&
        Objects.equals(this.snmpMode, discoveryNIO.snmpMode) &&
        Objects.equals(this.snmpPrivPassphrase, discoveryNIO.snmpPrivPassphrase) &&
        Objects.equals(this.snmpPrivProtocol, discoveryNIO.snmpPrivProtocol) &&
        Objects.equals(this.snmpRoCommunity, discoveryNIO.snmpRoCommunity) &&
        Objects.equals(this.snmpRoCommunityDesc, discoveryNIO.snmpRoCommunityDesc) &&
        Objects.equals(this.snmpRwCommunity, discoveryNIO.snmpRwCommunity) &&
        Objects.equals(this.snmpRwCommunityDesc, discoveryNIO.snmpRwCommunityDesc) &&
        Objects.equals(this.snmpUserName, discoveryNIO.snmpUserName) &&
        Objects.equals(this.timeOut, discoveryNIO.timeOut) &&
        Objects.equals(this.updateMgmtIp, discoveryNIO.updateMgmtIp) &&
        Objects.equals(this.userNameList, discoveryNIO.userNameList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeInfo, cdpLevel, deviceIds, discoveryCondition, discoveryStatus, discoveryType, enablePasswordList, globalCredentialIdList, httpReadCredential, httpWriteCredential, id, ipAddressList, ipFilterList, isAutoCdp, lldpLevel, name, netconfPort, numDevices, parentDiscoveryId, passwordList, preferredMgmtIPMethod, protocolOrder, retryCount, snmpAuthPassphrase, snmpAuthProtocol, snmpMode, snmpPrivPassphrase, snmpPrivProtocol, snmpRoCommunity, snmpRoCommunityDesc, snmpRwCommunity, snmpRwCommunityDesc, snmpUserName, timeOut, updateMgmtIp, userNameList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscoveryNIO {\n");
    
    sb.append("    attributeInfo: ").append(toIndentedString(attributeInfo)).append("\n");
    sb.append("    cdpLevel: ").append(toIndentedString(cdpLevel)).append("\n");
    sb.append("    deviceIds: ").append(toIndentedString(deviceIds)).append("\n");
    sb.append("    discoveryCondition: ").append(toIndentedString(discoveryCondition)).append("\n");
    sb.append("    discoveryStatus: ").append(toIndentedString(discoveryStatus)).append("\n");
    sb.append("    discoveryType: ").append(toIndentedString(discoveryType)).append("\n");
    sb.append("    enablePasswordList: ").append(toIndentedString(enablePasswordList)).append("\n");
    sb.append("    globalCredentialIdList: ").append(toIndentedString(globalCredentialIdList)).append("\n");
    sb.append("    httpReadCredential: ").append(toIndentedString(httpReadCredential)).append("\n");
    sb.append("    httpWriteCredential: ").append(toIndentedString(httpWriteCredential)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipAddressList: ").append(toIndentedString(ipAddressList)).append("\n");
    sb.append("    ipFilterList: ").append(toIndentedString(ipFilterList)).append("\n");
    sb.append("    isAutoCdp: ").append(toIndentedString(isAutoCdp)).append("\n");
    sb.append("    lldpLevel: ").append(toIndentedString(lldpLevel)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    netconfPort: ").append(toIndentedString(netconfPort)).append("\n");
    sb.append("    numDevices: ").append(toIndentedString(numDevices)).append("\n");
    sb.append("    parentDiscoveryId: ").append(toIndentedString(parentDiscoveryId)).append("\n");
    sb.append("    passwordList: ").append(toIndentedString(passwordList)).append("\n");
    sb.append("    preferredMgmtIPMethod: ").append(toIndentedString(preferredMgmtIPMethod)).append("\n");
    sb.append("    protocolOrder: ").append(toIndentedString(protocolOrder)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("    snmpAuthPassphrase: ").append(toIndentedString(snmpAuthPassphrase)).append("\n");
    sb.append("    snmpAuthProtocol: ").append(toIndentedString(snmpAuthProtocol)).append("\n");
    sb.append("    snmpMode: ").append(toIndentedString(snmpMode)).append("\n");
    sb.append("    snmpPrivPassphrase: ").append(toIndentedString(snmpPrivPassphrase)).append("\n");
    sb.append("    snmpPrivProtocol: ").append(toIndentedString(snmpPrivProtocol)).append("\n");
    sb.append("    snmpRoCommunity: ").append(toIndentedString(snmpRoCommunity)).append("\n");
    sb.append("    snmpRoCommunityDesc: ").append(toIndentedString(snmpRoCommunityDesc)).append("\n");
    sb.append("    snmpRwCommunity: ").append(toIndentedString(snmpRwCommunity)).append("\n");
    sb.append("    snmpRwCommunityDesc: ").append(toIndentedString(snmpRwCommunityDesc)).append("\n");
    sb.append("    snmpUserName: ").append(toIndentedString(snmpUserName)).append("\n");
    sb.append("    timeOut: ").append(toIndentedString(timeOut)).append("\n");
    sb.append("    updateMgmtIp: ").append(toIndentedString(updateMgmtIp)).append("\n");
    sb.append("    userNameList: ").append(toIndentedString(userNameList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

