/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FlowAnalysisRequestResultOutputResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class FlowAnalysisRequestResultOutputResponse {
  @SerializedName("flowAnalysisId")
  private String flowAnalysisId = null;

  @SerializedName("taskId")
  private String taskId = null;

  @SerializedName("url")
  private String url = null;

  public FlowAnalysisRequestResultOutputResponse flowAnalysisId(String flowAnalysisId) {
    this.flowAnalysisId = flowAnalysisId;
    return this;
  }

   /**
   * Get flowAnalysisId
   * @return flowAnalysisId
  **/
  @ApiModelProperty(value = "")
  public String getFlowAnalysisId() {
    return flowAnalysisId;
  }

  public void setFlowAnalysisId(String flowAnalysisId) {
    this.flowAnalysisId = flowAnalysisId;
  }

  public FlowAnalysisRequestResultOutputResponse taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(value = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public FlowAnalysisRequestResultOutputResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowAnalysisRequestResultOutputResponse flowAnalysisRequestResultOutputResponse = (FlowAnalysisRequestResultOutputResponse) o;
    return Objects.equals(this.flowAnalysisId, flowAnalysisRequestResultOutputResponse.flowAnalysisId) &&
        Objects.equals(this.taskId, flowAnalysisRequestResultOutputResponse.taskId) &&
        Objects.equals(this.url, flowAnalysisRequestResultOutputResponse.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowAnalysisId, taskId, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowAnalysisRequestResultOutputResponse {\n");
    
    sb.append("    flowAnalysisId: ").append(toIndentedString(flowAnalysisId)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

