/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FunctionalCapabilityListResultFunctionDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class FunctionalCapabilityListResultFunctionDetails {
  @SerializedName("attributeInfo")
  private Object attributeInfo = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("propertyName")
  private String propertyName = null;

  @SerializedName("stringValue")
  private String stringValue = null;

  public FunctionalCapabilityListResultFunctionDetails attributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
    return this;
  }

   /**
   * Get attributeInfo
   * @return attributeInfo
  **/
  @ApiModelProperty(value = "")
  public Object getAttributeInfo() {
    return attributeInfo;
  }

  public void setAttributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
  }

  public FunctionalCapabilityListResultFunctionDetails id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FunctionalCapabilityListResultFunctionDetails propertyName(String propertyName) {
    this.propertyName = propertyName;
    return this;
  }

   /**
   * Get propertyName
   * @return propertyName
  **/
  @ApiModelProperty(value = "")
  public String getPropertyName() {
    return propertyName;
  }

  public void setPropertyName(String propertyName) {
    this.propertyName = propertyName;
  }

  public FunctionalCapabilityListResultFunctionDetails stringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

   /**
   * Get stringValue
   * @return stringValue
  **/
  @ApiModelProperty(value = "")
  public String getStringValue() {
    return stringValue;
  }

  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionalCapabilityListResultFunctionDetails functionalCapabilityListResultFunctionDetails = (FunctionalCapabilityListResultFunctionDetails) o;
    return Objects.equals(this.attributeInfo, functionalCapabilityListResultFunctionDetails.attributeInfo) &&
        Objects.equals(this.id, functionalCapabilityListResultFunctionDetails.id) &&
        Objects.equals(this.propertyName, functionalCapabilityListResultFunctionDetails.propertyName) &&
        Objects.equals(this.stringValue, functionalCapabilityListResultFunctionDetails.stringValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeInfo, id, propertyName, stringValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionalCapabilityListResultFunctionDetails {\n");
    
    sb.append("    attributeInfo: ").append(toIndentedString(attributeInfo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    propertyName: ").append(toIndentedString(propertyName)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

