/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.FunctionalCapabilityListResultFunctionalCapability;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FunctionalCapabilityListResultResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class FunctionalCapabilityListResultResponse {
  @SerializedName("attributeInfo")
  private Object attributeInfo = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("functionalCapability")
  private List<FunctionalCapabilityListResultFunctionalCapability> functionalCapability = null;

  @SerializedName("id")
  private String id = null;

  public FunctionalCapabilityListResultResponse attributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
    return this;
  }

   /**
   * Get attributeInfo
   * @return attributeInfo
  **/
  @ApiModelProperty(value = "")
  public Object getAttributeInfo() {
    return attributeInfo;
  }

  public void setAttributeInfo(Object attributeInfo) {
    this.attributeInfo = attributeInfo;
  }

  public FunctionalCapabilityListResultResponse deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public FunctionalCapabilityListResultResponse functionalCapability(List<FunctionalCapabilityListResultFunctionalCapability> functionalCapability) {
    this.functionalCapability = functionalCapability;
    return this;
  }

  public FunctionalCapabilityListResultResponse addFunctionalCapabilityItem(FunctionalCapabilityListResultFunctionalCapability functionalCapabilityItem) {
    if (this.functionalCapability == null) {
      this.functionalCapability = new ArrayList<>();
    }
    this.functionalCapability.add(functionalCapabilityItem);
    return this;
  }

   /**
   * Get functionalCapability
   * @return functionalCapability
  **/
  @ApiModelProperty(value = "")
  public List<FunctionalCapabilityListResultFunctionalCapability> getFunctionalCapability() {
    return functionalCapability;
  }

  public void setFunctionalCapability(List<FunctionalCapabilityListResultFunctionalCapability> functionalCapability) {
    this.functionalCapability = functionalCapability;
  }

  public FunctionalCapabilityListResultResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionalCapabilityListResultResponse functionalCapabilityListResultResponse = (FunctionalCapabilityListResultResponse) o;
    return Objects.equals(this.attributeInfo, functionalCapabilityListResultResponse.attributeInfo) &&
        Objects.equals(this.deviceId, functionalCapabilityListResultResponse.deviceId) &&
        Objects.equals(this.functionalCapability, functionalCapabilityListResultResponse.functionalCapability) &&
        Objects.equals(this.id, functionalCapabilityListResultResponse.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeInfo, deviceId, functionalCapability, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionalCapabilityListResultResponse {\n");
    
    sb.append("    attributeInfo: ").append(toIndentedString(attributeInfo)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    functionalCapability: ").append(toIndentedString(functionalCapability)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

