/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.InventoryDeviceInfoUpdateMgmtIPaddressList;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InventoryDeviceInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class InventoryDeviceInfo {
  @SerializedName("cliTransport")
  private String cliTransport = null;

  @SerializedName("computeDevice")
  private Boolean computeDevice = null;

  @SerializedName("enablePassword")
  private String enablePassword = null;

  @SerializedName("extendedDiscoveryInfo")
  private String extendedDiscoveryInfo = null;

  @SerializedName("httpPassword")
  private String httpPassword = null;

  @SerializedName("httpPort")
  private String httpPort = null;

  @SerializedName("httpSecure")
  private Boolean httpSecure = null;

  @SerializedName("httpUserName")
  private String httpUserName = null;

  @SerializedName("ipAddress")
  private List<String> ipAddress = null;

  @SerializedName("merakiOrgId")
  private List<String> merakiOrgId = null;

  @SerializedName("netconfPort")
  private String netconfPort = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("snmpAuthPassphrase")
  private String snmpAuthPassphrase = null;

  @SerializedName("snmpAuthProtocol")
  private String snmpAuthProtocol = null;

  @SerializedName("snmpMode")
  private String snmpMode = null;

  @SerializedName("snmpPrivPassphrase")
  private String snmpPrivPassphrase = null;

  @SerializedName("snmpPrivProtocol")
  private String snmpPrivProtocol = null;

  @SerializedName("snmpROCommunity")
  private String snmpROCommunity = null;

  @SerializedName("snmpRWCommunity")
  private String snmpRWCommunity = null;

  @SerializedName("snmpRetry")
  private Integer snmpRetry = null;

  @SerializedName("snmpTimeout")
  private Integer snmpTimeout = null;

  @SerializedName("snmpUserName")
  private String snmpUserName = null;

  @SerializedName("snmpVersion")
  private String snmpVersion = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    COMPUTE_DEVICE("COMPUTE_DEVICE"),
    
    MERAKI_DASHBOARD("MERAKI_DASHBOARD"),
    
    NETWORK_DEVICE("NETWORK_DEVICE"),
    
    NODATACHANGE("NODATACHANGE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("updateMgmtIPaddressList")
  private List<InventoryDeviceInfoUpdateMgmtIPaddressList> updateMgmtIPaddressList = null;

  @SerializedName("userName")
  private String userName = null;

  public InventoryDeviceInfo cliTransport(String cliTransport) {
    this.cliTransport = cliTransport;
    return this;
  }

   /**
   * Get cliTransport
   * @return cliTransport
  **/
  @ApiModelProperty(value = "")
  public String getCliTransport() {
    return cliTransport;
  }

  public void setCliTransport(String cliTransport) {
    this.cliTransport = cliTransport;
  }

  public InventoryDeviceInfo computeDevice(Boolean computeDevice) {
    this.computeDevice = computeDevice;
    return this;
  }

   /**
   * Get computeDevice
   * @return computeDevice
  **/
  @ApiModelProperty(value = "")
  public Boolean isComputeDevice() {
    return computeDevice;
  }

  public void setComputeDevice(Boolean computeDevice) {
    this.computeDevice = computeDevice;
  }

  public InventoryDeviceInfo enablePassword(String enablePassword) {
    this.enablePassword = enablePassword;
    return this;
  }

   /**
   * Get enablePassword
   * @return enablePassword
  **/
  @ApiModelProperty(value = "")
  public String getEnablePassword() {
    return enablePassword;
  }

  public void setEnablePassword(String enablePassword) {
    this.enablePassword = enablePassword;
  }

  public InventoryDeviceInfo extendedDiscoveryInfo(String extendedDiscoveryInfo) {
    this.extendedDiscoveryInfo = extendedDiscoveryInfo;
    return this;
  }

   /**
   * Get extendedDiscoveryInfo
   * @return extendedDiscoveryInfo
  **/
  @ApiModelProperty(value = "")
  public String getExtendedDiscoveryInfo() {
    return extendedDiscoveryInfo;
  }

  public void setExtendedDiscoveryInfo(String extendedDiscoveryInfo) {
    this.extendedDiscoveryInfo = extendedDiscoveryInfo;
  }

  public InventoryDeviceInfo httpPassword(String httpPassword) {
    this.httpPassword = httpPassword;
    return this;
  }

   /**
   * Get httpPassword
   * @return httpPassword
  **/
  @ApiModelProperty(value = "")
  public String getHttpPassword() {
    return httpPassword;
  }

  public void setHttpPassword(String httpPassword) {
    this.httpPassword = httpPassword;
  }

  public InventoryDeviceInfo httpPort(String httpPort) {
    this.httpPort = httpPort;
    return this;
  }

   /**
   * Get httpPort
   * @return httpPort
  **/
  @ApiModelProperty(value = "")
  public String getHttpPort() {
    return httpPort;
  }

  public void setHttpPort(String httpPort) {
    this.httpPort = httpPort;
  }

  public InventoryDeviceInfo httpSecure(Boolean httpSecure) {
    this.httpSecure = httpSecure;
    return this;
  }

   /**
   * Get httpSecure
   * @return httpSecure
  **/
  @ApiModelProperty(value = "")
  public Boolean isHttpSecure() {
    return httpSecure;
  }

  public void setHttpSecure(Boolean httpSecure) {
    this.httpSecure = httpSecure;
  }

  public InventoryDeviceInfo httpUserName(String httpUserName) {
    this.httpUserName = httpUserName;
    return this;
  }

   /**
   * Get httpUserName
   * @return httpUserName
  **/
  @ApiModelProperty(value = "")
  public String getHttpUserName() {
    return httpUserName;
  }

  public void setHttpUserName(String httpUserName) {
    this.httpUserName = httpUserName;
  }

  public InventoryDeviceInfo ipAddress(List<String> ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  public InventoryDeviceInfo addIpAddressItem(String ipAddressItem) {
    if (this.ipAddress == null) {
      this.ipAddress = new ArrayList<>();
    }
    this.ipAddress.add(ipAddressItem);
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(List<String> ipAddress) {
    this.ipAddress = ipAddress;
  }

  public InventoryDeviceInfo merakiOrgId(List<String> merakiOrgId) {
    this.merakiOrgId = merakiOrgId;
    return this;
  }

  public InventoryDeviceInfo addMerakiOrgIdItem(String merakiOrgIdItem) {
    if (this.merakiOrgId == null) {
      this.merakiOrgId = new ArrayList<>();
    }
    this.merakiOrgId.add(merakiOrgIdItem);
    return this;
  }

   /**
   * Get merakiOrgId
   * @return merakiOrgId
  **/
  @ApiModelProperty(value = "")
  public List<String> getMerakiOrgId() {
    return merakiOrgId;
  }

  public void setMerakiOrgId(List<String> merakiOrgId) {
    this.merakiOrgId = merakiOrgId;
  }

  public InventoryDeviceInfo netconfPort(String netconfPort) {
    this.netconfPort = netconfPort;
    return this;
  }

   /**
   * Get netconfPort
   * @return netconfPort
  **/
  @ApiModelProperty(value = "")
  public String getNetconfPort() {
    return netconfPort;
  }

  public void setNetconfPort(String netconfPort) {
    this.netconfPort = netconfPort;
  }

  public InventoryDeviceInfo password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public InventoryDeviceInfo serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @ApiModelProperty(value = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public InventoryDeviceInfo snmpAuthPassphrase(String snmpAuthPassphrase) {
    this.snmpAuthPassphrase = snmpAuthPassphrase;
    return this;
  }

   /**
   * Get snmpAuthPassphrase
   * @return snmpAuthPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getSnmpAuthPassphrase() {
    return snmpAuthPassphrase;
  }

  public void setSnmpAuthPassphrase(String snmpAuthPassphrase) {
    this.snmpAuthPassphrase = snmpAuthPassphrase;
  }

  public InventoryDeviceInfo snmpAuthProtocol(String snmpAuthProtocol) {
    this.snmpAuthProtocol = snmpAuthProtocol;
    return this;
  }

   /**
   * Get snmpAuthProtocol
   * @return snmpAuthProtocol
  **/
  @ApiModelProperty(value = "")
  public String getSnmpAuthProtocol() {
    return snmpAuthProtocol;
  }

  public void setSnmpAuthProtocol(String snmpAuthProtocol) {
    this.snmpAuthProtocol = snmpAuthProtocol;
  }

  public InventoryDeviceInfo snmpMode(String snmpMode) {
    this.snmpMode = snmpMode;
    return this;
  }

   /**
   * Get snmpMode
   * @return snmpMode
  **/
  @ApiModelProperty(value = "")
  public String getSnmpMode() {
    return snmpMode;
  }

  public void setSnmpMode(String snmpMode) {
    this.snmpMode = snmpMode;
  }

  public InventoryDeviceInfo snmpPrivPassphrase(String snmpPrivPassphrase) {
    this.snmpPrivPassphrase = snmpPrivPassphrase;
    return this;
  }

   /**
   * Get snmpPrivPassphrase
   * @return snmpPrivPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getSnmpPrivPassphrase() {
    return snmpPrivPassphrase;
  }

  public void setSnmpPrivPassphrase(String snmpPrivPassphrase) {
    this.snmpPrivPassphrase = snmpPrivPassphrase;
  }

  public InventoryDeviceInfo snmpPrivProtocol(String snmpPrivProtocol) {
    this.snmpPrivProtocol = snmpPrivProtocol;
    return this;
  }

   /**
   * Get snmpPrivProtocol
   * @return snmpPrivProtocol
  **/
  @ApiModelProperty(value = "")
  public String getSnmpPrivProtocol() {
    return snmpPrivProtocol;
  }

  public void setSnmpPrivProtocol(String snmpPrivProtocol) {
    this.snmpPrivProtocol = snmpPrivProtocol;
  }

  public InventoryDeviceInfo snmpROCommunity(String snmpROCommunity) {
    this.snmpROCommunity = snmpROCommunity;
    return this;
  }

   /**
   * Get snmpROCommunity
   * @return snmpROCommunity
  **/
  @ApiModelProperty(value = "")
  public String getSnmpROCommunity() {
    return snmpROCommunity;
  }

  public void setSnmpROCommunity(String snmpROCommunity) {
    this.snmpROCommunity = snmpROCommunity;
  }

  public InventoryDeviceInfo snmpRWCommunity(String snmpRWCommunity) {
    this.snmpRWCommunity = snmpRWCommunity;
    return this;
  }

   /**
   * Get snmpRWCommunity
   * @return snmpRWCommunity
  **/
  @ApiModelProperty(value = "")
  public String getSnmpRWCommunity() {
    return snmpRWCommunity;
  }

  public void setSnmpRWCommunity(String snmpRWCommunity) {
    this.snmpRWCommunity = snmpRWCommunity;
  }

  public InventoryDeviceInfo snmpRetry(Integer snmpRetry) {
    this.snmpRetry = snmpRetry;
    return this;
  }

   /**
   * Get snmpRetry
   * @return snmpRetry
  **/
  @ApiModelProperty(value = "")
  public Integer getSnmpRetry() {
    return snmpRetry;
  }

  public void setSnmpRetry(Integer snmpRetry) {
    this.snmpRetry = snmpRetry;
  }

  public InventoryDeviceInfo snmpTimeout(Integer snmpTimeout) {
    this.snmpTimeout = snmpTimeout;
    return this;
  }

   /**
   * Get snmpTimeout
   * @return snmpTimeout
  **/
  @ApiModelProperty(value = "")
  public Integer getSnmpTimeout() {
    return snmpTimeout;
  }

  public void setSnmpTimeout(Integer snmpTimeout) {
    this.snmpTimeout = snmpTimeout;
  }

  public InventoryDeviceInfo snmpUserName(String snmpUserName) {
    this.snmpUserName = snmpUserName;
    return this;
  }

   /**
   * Get snmpUserName
   * @return snmpUserName
  **/
  @ApiModelProperty(value = "")
  public String getSnmpUserName() {
    return snmpUserName;
  }

  public void setSnmpUserName(String snmpUserName) {
    this.snmpUserName = snmpUserName;
  }

  public InventoryDeviceInfo snmpVersion(String snmpVersion) {
    this.snmpVersion = snmpVersion;
    return this;
  }

   /**
   * Get snmpVersion
   * @return snmpVersion
  **/
  @ApiModelProperty(value = "")
  public String getSnmpVersion() {
    return snmpVersion;
  }

  public void setSnmpVersion(String snmpVersion) {
    this.snmpVersion = snmpVersion;
  }

  public InventoryDeviceInfo type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public InventoryDeviceInfo updateMgmtIPaddressList(List<InventoryDeviceInfoUpdateMgmtIPaddressList> updateMgmtIPaddressList) {
    this.updateMgmtIPaddressList = updateMgmtIPaddressList;
    return this;
  }

  public InventoryDeviceInfo addUpdateMgmtIPaddressListItem(InventoryDeviceInfoUpdateMgmtIPaddressList updateMgmtIPaddressListItem) {
    if (this.updateMgmtIPaddressList == null) {
      this.updateMgmtIPaddressList = new ArrayList<>();
    }
    this.updateMgmtIPaddressList.add(updateMgmtIPaddressListItem);
    return this;
  }

   /**
   * Get updateMgmtIPaddressList
   * @return updateMgmtIPaddressList
  **/
  @ApiModelProperty(value = "")
  public List<InventoryDeviceInfoUpdateMgmtIPaddressList> getUpdateMgmtIPaddressList() {
    return updateMgmtIPaddressList;
  }

  public void setUpdateMgmtIPaddressList(List<InventoryDeviceInfoUpdateMgmtIPaddressList> updateMgmtIPaddressList) {
    this.updateMgmtIPaddressList = updateMgmtIPaddressList;
  }

  public InventoryDeviceInfo userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryDeviceInfo inventoryDeviceInfo = (InventoryDeviceInfo) o;
    return Objects.equals(this.cliTransport, inventoryDeviceInfo.cliTransport) &&
        Objects.equals(this.computeDevice, inventoryDeviceInfo.computeDevice) &&
        Objects.equals(this.enablePassword, inventoryDeviceInfo.enablePassword) &&
        Objects.equals(this.extendedDiscoveryInfo, inventoryDeviceInfo.extendedDiscoveryInfo) &&
        Objects.equals(this.httpPassword, inventoryDeviceInfo.httpPassword) &&
        Objects.equals(this.httpPort, inventoryDeviceInfo.httpPort) &&
        Objects.equals(this.httpSecure, inventoryDeviceInfo.httpSecure) &&
        Objects.equals(this.httpUserName, inventoryDeviceInfo.httpUserName) &&
        Objects.equals(this.ipAddress, inventoryDeviceInfo.ipAddress) &&
        Objects.equals(this.merakiOrgId, inventoryDeviceInfo.merakiOrgId) &&
        Objects.equals(this.netconfPort, inventoryDeviceInfo.netconfPort) &&
        Objects.equals(this.password, inventoryDeviceInfo.password) &&
        Objects.equals(this.serialNumber, inventoryDeviceInfo.serialNumber) &&
        Objects.equals(this.snmpAuthPassphrase, inventoryDeviceInfo.snmpAuthPassphrase) &&
        Objects.equals(this.snmpAuthProtocol, inventoryDeviceInfo.snmpAuthProtocol) &&
        Objects.equals(this.snmpMode, inventoryDeviceInfo.snmpMode) &&
        Objects.equals(this.snmpPrivPassphrase, inventoryDeviceInfo.snmpPrivPassphrase) &&
        Objects.equals(this.snmpPrivProtocol, inventoryDeviceInfo.snmpPrivProtocol) &&
        Objects.equals(this.snmpROCommunity, inventoryDeviceInfo.snmpROCommunity) &&
        Objects.equals(this.snmpRWCommunity, inventoryDeviceInfo.snmpRWCommunity) &&
        Objects.equals(this.snmpRetry, inventoryDeviceInfo.snmpRetry) &&
        Objects.equals(this.snmpTimeout, inventoryDeviceInfo.snmpTimeout) &&
        Objects.equals(this.snmpUserName, inventoryDeviceInfo.snmpUserName) &&
        Objects.equals(this.snmpVersion, inventoryDeviceInfo.snmpVersion) &&
        Objects.equals(this.type, inventoryDeviceInfo.type) &&
        Objects.equals(this.updateMgmtIPaddressList, inventoryDeviceInfo.updateMgmtIPaddressList) &&
        Objects.equals(this.userName, inventoryDeviceInfo.userName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliTransport, computeDevice, enablePassword, extendedDiscoveryInfo, httpPassword, httpPort, httpSecure, httpUserName, ipAddress, merakiOrgId, netconfPort, password, serialNumber, snmpAuthPassphrase, snmpAuthProtocol, snmpMode, snmpPrivPassphrase, snmpPrivProtocol, snmpROCommunity, snmpRWCommunity, snmpRetry, snmpTimeout, snmpUserName, snmpVersion, type, updateMgmtIPaddressList, userName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryDeviceInfo {\n");
    
    sb.append("    cliTransport: ").append(toIndentedString(cliTransport)).append("\n");
    sb.append("    computeDevice: ").append(toIndentedString(computeDevice)).append("\n");
    sb.append("    enablePassword: ").append(toIndentedString(enablePassword)).append("\n");
    sb.append("    extendedDiscoveryInfo: ").append(toIndentedString(extendedDiscoveryInfo)).append("\n");
    sb.append("    httpPassword: ").append(toIndentedString(httpPassword)).append("\n");
    sb.append("    httpPort: ").append(toIndentedString(httpPort)).append("\n");
    sb.append("    httpSecure: ").append(toIndentedString(httpSecure)).append("\n");
    sb.append("    httpUserName: ").append(toIndentedString(httpUserName)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    merakiOrgId: ").append(toIndentedString(merakiOrgId)).append("\n");
    sb.append("    netconfPort: ").append(toIndentedString(netconfPort)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    snmpAuthPassphrase: ").append(toIndentedString(snmpAuthPassphrase)).append("\n");
    sb.append("    snmpAuthProtocol: ").append(toIndentedString(snmpAuthProtocol)).append("\n");
    sb.append("    snmpMode: ").append(toIndentedString(snmpMode)).append("\n");
    sb.append("    snmpPrivPassphrase: ").append(toIndentedString(snmpPrivPassphrase)).append("\n");
    sb.append("    snmpPrivProtocol: ").append(toIndentedString(snmpPrivProtocol)).append("\n");
    sb.append("    snmpROCommunity: ").append(toIndentedString(snmpROCommunity)).append("\n");
    sb.append("    snmpRWCommunity: ").append(toIndentedString(snmpRWCommunity)).append("\n");
    sb.append("    snmpRetry: ").append(toIndentedString(snmpRetry)).append("\n");
    sb.append("    snmpTimeout: ").append(toIndentedString(snmpTimeout)).append("\n");
    sb.append("    snmpUserName: ").append(toIndentedString(snmpUserName)).append("\n");
    sb.append("    snmpVersion: ").append(toIndentedString(snmpVersion)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updateMgmtIPaddressList: ").append(toIndentedString(updateMgmtIPaddressList)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

