/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NetworkDeviceDetailResponseResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class NetworkDeviceDetailResponseResponse {
  @SerializedName("managementIpAddr")
  private String managementIpAddr = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("nwDeviceName")
  private String nwDeviceName = null;

  @SerializedName("opState")
  private String opState = null;

  @SerializedName("platformId")
  private String platformId = null;

  @SerializedName("nwDeviceId")
  private String nwDeviceId = null;

  @SerializedName("sysUptime")
  private String sysUptime = null;

  @SerializedName("mode")
  private String mode = null;

  @SerializedName("resetReason")
  private String resetReason = null;

  @SerializedName("nwDeviceRole")
  private String nwDeviceRole = null;

  @SerializedName("upTime")
  private String upTime = null;

  @SerializedName("nwDeviceFamily")
  private String nwDeviceFamily = null;

  @SerializedName("macAddress")
  private String macAddress = null;

  @SerializedName("connectedTime")
  private String connectedTime = null;

  @SerializedName("softwareVersion")
  private String softwareVersion = null;

  @SerializedName("subMode")
  private String subMode = null;

  @SerializedName("nwDeviceType")
  private String nwDeviceType = null;

  @SerializedName("overallHealth")
  private String overallHealth = null;

  @SerializedName("memoryScore")
  private String memoryScore = null;

  @SerializedName("cpuScore")
  private String cpuScore = null;

  public NetworkDeviceDetailResponseResponse managementIpAddr(String managementIpAddr) {
    this.managementIpAddr = managementIpAddr;
    return this;
  }

   /**
   * Get managementIpAddr
   * @return managementIpAddr
  **/
  @ApiModelProperty(value = "")
  public String getManagementIpAddr() {
    return managementIpAddr;
  }

  public void setManagementIpAddr(String managementIpAddr) {
    this.managementIpAddr = managementIpAddr;
  }

  public NetworkDeviceDetailResponseResponse serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @ApiModelProperty(value = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public NetworkDeviceDetailResponseResponse nwDeviceName(String nwDeviceName) {
    this.nwDeviceName = nwDeviceName;
    return this;
  }

   /**
   * Get nwDeviceName
   * @return nwDeviceName
  **/
  @ApiModelProperty(value = "")
  public String getNwDeviceName() {
    return nwDeviceName;
  }

  public void setNwDeviceName(String nwDeviceName) {
    this.nwDeviceName = nwDeviceName;
  }

  public NetworkDeviceDetailResponseResponse opState(String opState) {
    this.opState = opState;
    return this;
  }

   /**
   * Get opState
   * @return opState
  **/
  @ApiModelProperty(value = "")
  public String getOpState() {
    return opState;
  }

  public void setOpState(String opState) {
    this.opState = opState;
  }

  public NetworkDeviceDetailResponseResponse platformId(String platformId) {
    this.platformId = platformId;
    return this;
  }

   /**
   * Get platformId
   * @return platformId
  **/
  @ApiModelProperty(value = "")
  public String getPlatformId() {
    return platformId;
  }

  public void setPlatformId(String platformId) {
    this.platformId = platformId;
  }

  public NetworkDeviceDetailResponseResponse nwDeviceId(String nwDeviceId) {
    this.nwDeviceId = nwDeviceId;
    return this;
  }

   /**
   * Get nwDeviceId
   * @return nwDeviceId
  **/
  @ApiModelProperty(value = "")
  public String getNwDeviceId() {
    return nwDeviceId;
  }

  public void setNwDeviceId(String nwDeviceId) {
    this.nwDeviceId = nwDeviceId;
  }

  public NetworkDeviceDetailResponseResponse sysUptime(String sysUptime) {
    this.sysUptime = sysUptime;
    return this;
  }

   /**
   * Get sysUptime
   * @return sysUptime
  **/
  @ApiModelProperty(value = "")
  public String getSysUptime() {
    return sysUptime;
  }

  public void setSysUptime(String sysUptime) {
    this.sysUptime = sysUptime;
  }

  public NetworkDeviceDetailResponseResponse mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(value = "")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public NetworkDeviceDetailResponseResponse resetReason(String resetReason) {
    this.resetReason = resetReason;
    return this;
  }

   /**
   * Get resetReason
   * @return resetReason
  **/
  @ApiModelProperty(value = "")
  public String getResetReason() {
    return resetReason;
  }

  public void setResetReason(String resetReason) {
    this.resetReason = resetReason;
  }

  public NetworkDeviceDetailResponseResponse nwDeviceRole(String nwDeviceRole) {
    this.nwDeviceRole = nwDeviceRole;
    return this;
  }

   /**
   * Get nwDeviceRole
   * @return nwDeviceRole
  **/
  @ApiModelProperty(value = "")
  public String getNwDeviceRole() {
    return nwDeviceRole;
  }

  public void setNwDeviceRole(String nwDeviceRole) {
    this.nwDeviceRole = nwDeviceRole;
  }

  public NetworkDeviceDetailResponseResponse upTime(String upTime) {
    this.upTime = upTime;
    return this;
  }

   /**
   * Get upTime
   * @return upTime
  **/
  @ApiModelProperty(value = "")
  public String getUpTime() {
    return upTime;
  }

  public void setUpTime(String upTime) {
    this.upTime = upTime;
  }

  public NetworkDeviceDetailResponseResponse nwDeviceFamily(String nwDeviceFamily) {
    this.nwDeviceFamily = nwDeviceFamily;
    return this;
  }

   /**
   * Get nwDeviceFamily
   * @return nwDeviceFamily
  **/
  @ApiModelProperty(value = "")
  public String getNwDeviceFamily() {
    return nwDeviceFamily;
  }

  public void setNwDeviceFamily(String nwDeviceFamily) {
    this.nwDeviceFamily = nwDeviceFamily;
  }

  public NetworkDeviceDetailResponseResponse macAddress(String macAddress) {
    this.macAddress = macAddress;
    return this;
  }

   /**
   * Get macAddress
   * @return macAddress
  **/
  @ApiModelProperty(value = "")
  public String getMacAddress() {
    return macAddress;
  }

  public void setMacAddress(String macAddress) {
    this.macAddress = macAddress;
  }

  public NetworkDeviceDetailResponseResponse connectedTime(String connectedTime) {
    this.connectedTime = connectedTime;
    return this;
  }

   /**
   * Get connectedTime
   * @return connectedTime
  **/
  @ApiModelProperty(value = "")
  public String getConnectedTime() {
    return connectedTime;
  }

  public void setConnectedTime(String connectedTime) {
    this.connectedTime = connectedTime;
  }

  public NetworkDeviceDetailResponseResponse softwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
    return this;
  }

   /**
   * Get softwareVersion
   * @return softwareVersion
  **/
  @ApiModelProperty(value = "")
  public String getSoftwareVersion() {
    return softwareVersion;
  }

  public void setSoftwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public NetworkDeviceDetailResponseResponse subMode(String subMode) {
    this.subMode = subMode;
    return this;
  }

   /**
   * Get subMode
   * @return subMode
  **/
  @ApiModelProperty(value = "")
  public String getSubMode() {
    return subMode;
  }

  public void setSubMode(String subMode) {
    this.subMode = subMode;
  }

  public NetworkDeviceDetailResponseResponse nwDeviceType(String nwDeviceType) {
    this.nwDeviceType = nwDeviceType;
    return this;
  }

   /**
   * Get nwDeviceType
   * @return nwDeviceType
  **/
  @ApiModelProperty(value = "")
  public String getNwDeviceType() {
    return nwDeviceType;
  }

  public void setNwDeviceType(String nwDeviceType) {
    this.nwDeviceType = nwDeviceType;
  }

  public NetworkDeviceDetailResponseResponse overallHealth(String overallHealth) {
    this.overallHealth = overallHealth;
    return this;
  }

   /**
   * Get overallHealth
   * @return overallHealth
  **/
  @ApiModelProperty(value = "")
  public String getOverallHealth() {
    return overallHealth;
  }

  public void setOverallHealth(String overallHealth) {
    this.overallHealth = overallHealth;
  }

  public NetworkDeviceDetailResponseResponse memoryScore(String memoryScore) {
    this.memoryScore = memoryScore;
    return this;
  }

   /**
   * Get memoryScore
   * @return memoryScore
  **/
  @ApiModelProperty(value = "")
  public String getMemoryScore() {
    return memoryScore;
  }

  public void setMemoryScore(String memoryScore) {
    this.memoryScore = memoryScore;
  }

  public NetworkDeviceDetailResponseResponse cpuScore(String cpuScore) {
    this.cpuScore = cpuScore;
    return this;
  }

   /**
   * Get cpuScore
   * @return cpuScore
  **/
  @ApiModelProperty(value = "")
  public String getCpuScore() {
    return cpuScore;
  }

  public void setCpuScore(String cpuScore) {
    this.cpuScore = cpuScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkDeviceDetailResponseResponse networkDeviceDetailResponseResponse = (NetworkDeviceDetailResponseResponse) o;
    return Objects.equals(this.managementIpAddr, networkDeviceDetailResponseResponse.managementIpAddr) &&
        Objects.equals(this.serialNumber, networkDeviceDetailResponseResponse.serialNumber) &&
        Objects.equals(this.nwDeviceName, networkDeviceDetailResponseResponse.nwDeviceName) &&
        Objects.equals(this.opState, networkDeviceDetailResponseResponse.opState) &&
        Objects.equals(this.platformId, networkDeviceDetailResponseResponse.platformId) &&
        Objects.equals(this.nwDeviceId, networkDeviceDetailResponseResponse.nwDeviceId) &&
        Objects.equals(this.sysUptime, networkDeviceDetailResponseResponse.sysUptime) &&
        Objects.equals(this.mode, networkDeviceDetailResponseResponse.mode) &&
        Objects.equals(this.resetReason, networkDeviceDetailResponseResponse.resetReason) &&
        Objects.equals(this.nwDeviceRole, networkDeviceDetailResponseResponse.nwDeviceRole) &&
        Objects.equals(this.upTime, networkDeviceDetailResponseResponse.upTime) &&
        Objects.equals(this.nwDeviceFamily, networkDeviceDetailResponseResponse.nwDeviceFamily) &&
        Objects.equals(this.macAddress, networkDeviceDetailResponseResponse.macAddress) &&
        Objects.equals(this.connectedTime, networkDeviceDetailResponseResponse.connectedTime) &&
        Objects.equals(this.softwareVersion, networkDeviceDetailResponseResponse.softwareVersion) &&
        Objects.equals(this.subMode, networkDeviceDetailResponseResponse.subMode) &&
        Objects.equals(this.nwDeviceType, networkDeviceDetailResponseResponse.nwDeviceType) &&
        Objects.equals(this.overallHealth, networkDeviceDetailResponseResponse.overallHealth) &&
        Objects.equals(this.memoryScore, networkDeviceDetailResponseResponse.memoryScore) &&
        Objects.equals(this.cpuScore, networkDeviceDetailResponseResponse.cpuScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(managementIpAddr, serialNumber, nwDeviceName, opState, platformId, nwDeviceId, sysUptime, mode, resetReason, nwDeviceRole, upTime, nwDeviceFamily, macAddress, connectedTime, softwareVersion, subMode, nwDeviceType, overallHealth, memoryScore, cpuScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkDeviceDetailResponseResponse {\n");
    
    sb.append("    managementIpAddr: ").append(toIndentedString(managementIpAddr)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    nwDeviceName: ").append(toIndentedString(nwDeviceName)).append("\n");
    sb.append("    opState: ").append(toIndentedString(opState)).append("\n");
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("    nwDeviceId: ").append(toIndentedString(nwDeviceId)).append("\n");
    sb.append("    sysUptime: ").append(toIndentedString(sysUptime)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    resetReason: ").append(toIndentedString(resetReason)).append("\n");
    sb.append("    nwDeviceRole: ").append(toIndentedString(nwDeviceRole)).append("\n");
    sb.append("    upTime: ").append(toIndentedString(upTime)).append("\n");
    sb.append("    nwDeviceFamily: ").append(toIndentedString(nwDeviceFamily)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    connectedTime: ").append(toIndentedString(connectedTime)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    subMode: ").append(toIndentedString(subMode)).append("\n");
    sb.append("    nwDeviceType: ").append(toIndentedString(nwDeviceType)).append("\n");
    sb.append("    overallHealth: ").append(toIndentedString(overallHealth)).append("\n");
    sb.append("    memoryScore: ").append(toIndentedString(memoryScore)).append("\n");
    sb.append("    cpuScore: ").append(toIndentedString(cpuScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

