/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo {
  @SerializedName("dscp")
  private String dscp = null;

  @SerializedName("vnid")
  private String vnid = null;

  public PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo dscp(String dscp) {
    this.dscp = dscp;
    return this;
  }

   /**
   * Get dscp
   * @return dscp
  **/
  @ApiModelProperty(value = "")
  public String getDscp() {
    return dscp;
  }

  public void setDscp(String dscp) {
    this.dscp = dscp;
  }

  public PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo vnid(String vnid) {
    this.vnid = vnid;
    return this;
  }

   /**
   * Get vnid
   * @return vnid
  **/
  @ApiModelProperty(value = "")
  public String getVnid() {
    return vnid;
  }

  public void setVnid(String vnid) {
    this.vnid = vnid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo pathResponseResultResponseEgressPhysicalInterfaceVxlanInfo = (PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo) o;
    return Objects.equals(this.dscp, pathResponseResultResponseEgressPhysicalInterfaceVxlanInfo.dscp) &&
        Objects.equals(this.vnid, pathResponseResultResponseEgressPhysicalInterfaceVxlanInfo.vnid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dscp, vnid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathResponseResultResponseEgressPhysicalInterfaceVxlanInfo {\n");
    
    sb.append("    dscp: ").append(toIndentedString(dscp)).append("\n");
    sb.append("    vnid: ").append(toIndentedString(vnid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

