/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces {
  @SerializedName("ace")
  private String ace = null;

  @SerializedName("matchingPorts")
  private List<PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts> matchingPorts = null;

  @SerializedName("result")
  private String result = null;

  public PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces ace(String ace) {
    this.ace = ace;
    return this;
  }

   /**
   * Get ace
   * @return ace
  **/
  @ApiModelProperty(value = "")
  public String getAce() {
    return ace;
  }

  public void setAce(String ace) {
    this.ace = ace;
  }

  public PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces matchingPorts(List<PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts> matchingPorts) {
    this.matchingPorts = matchingPorts;
    return this;
  }

  public PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces addMatchingPortsItem(PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts matchingPortsItem) {
    if (this.matchingPorts == null) {
      this.matchingPorts = new ArrayList<>();
    }
    this.matchingPorts.add(matchingPortsItem);
    return this;
  }

   /**
   * Get matchingPorts
   * @return matchingPorts
  **/
  @ApiModelProperty(value = "")
  public List<PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts> getMatchingPorts() {
    return matchingPorts;
  }

  public void setMatchingPorts(List<PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingPorts> matchingPorts) {
    this.matchingPorts = matchingPorts;
  }

  public PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces pathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces = (PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces) o;
    return Objects.equals(this.ace, pathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces.ace) &&
        Objects.equals(this.matchingPorts, pathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces.matchingPorts) &&
        Objects.equals(this.result, pathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ace, matchingPorts, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces {\n");
    
    sb.append("    ace: ").append(toIndentedString(ace)).append("\n");
    sb.append("    matchingPorts: ").append(toIndentedString(matchingPorts)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

