/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PathResponseResultResponseDeviceStatisticsMemoryStatistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class PathResponseResultResponseDeviceStatisticsMemoryStatistics {
  @SerializedName("memoryUsage")
  private Integer memoryUsage = null;

  @SerializedName("refreshedAt")
  private Integer refreshedAt = null;

  @SerializedName("totalMemory")
  private Integer totalMemory = null;

  public PathResponseResultResponseDeviceStatisticsMemoryStatistics memoryUsage(Integer memoryUsage) {
    this.memoryUsage = memoryUsage;
    return this;
  }

   /**
   * Get memoryUsage
   * @return memoryUsage
  **/
  @ApiModelProperty(value = "")
  public Integer getMemoryUsage() {
    return memoryUsage;
  }

  public void setMemoryUsage(Integer memoryUsage) {
    this.memoryUsage = memoryUsage;
  }

  public PathResponseResultResponseDeviceStatisticsMemoryStatistics refreshedAt(Integer refreshedAt) {
    this.refreshedAt = refreshedAt;
    return this;
  }

   /**
   * Get refreshedAt
   * @return refreshedAt
  **/
  @ApiModelProperty(value = "")
  public Integer getRefreshedAt() {
    return refreshedAt;
  }

  public void setRefreshedAt(Integer refreshedAt) {
    this.refreshedAt = refreshedAt;
  }

  public PathResponseResultResponseDeviceStatisticsMemoryStatistics totalMemory(Integer totalMemory) {
    this.totalMemory = totalMemory;
    return this;
  }

   /**
   * Get totalMemory
   * @return totalMemory
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalMemory() {
    return totalMemory;
  }

  public void setTotalMemory(Integer totalMemory) {
    this.totalMemory = totalMemory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathResponseResultResponseDeviceStatisticsMemoryStatistics pathResponseResultResponseDeviceStatisticsMemoryStatistics = (PathResponseResultResponseDeviceStatisticsMemoryStatistics) o;
    return Objects.equals(this.memoryUsage, pathResponseResultResponseDeviceStatisticsMemoryStatistics.memoryUsage) &&
        Objects.equals(this.refreshedAt, pathResponseResultResponseDeviceStatisticsMemoryStatistics.refreshedAt) &&
        Objects.equals(this.totalMemory, pathResponseResultResponseDeviceStatisticsMemoryStatistics.totalMemory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memoryUsage, refreshedAt, totalMemory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathResponseResultResponseDeviceStatisticsMemoryStatistics {\n");
    
    sb.append("    memoryUsage: ").append(toIndentedString(memoryUsage)).append("\n");
    sb.append("    refreshedAt: ").append(toIndentedString(refreshedAt)).append("\n");
    sb.append("    totalMemory: ").append(toIndentedString(totalMemory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

