/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SettingsDefaultProfile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class SettingsDefaultProfile {
  @SerializedName("cert")
  private String cert = null;

  @SerializedName("fqdnAddresses")
  private List<String> fqdnAddresses = null;

  @SerializedName("ipAddresses")
  private List<String> ipAddresses = null;

  @SerializedName("port")
  private Integer port = null;

  @SerializedName("proxy")
  private Boolean proxy = null;

  public SettingsDefaultProfile cert(String cert) {
    this.cert = cert;
    return this;
  }

   /**
   * Get cert
   * @return cert
  **/
  @ApiModelProperty(value = "")
  public String getCert() {
    return cert;
  }

  public void setCert(String cert) {
    this.cert = cert;
  }

  public SettingsDefaultProfile fqdnAddresses(List<String> fqdnAddresses) {
    this.fqdnAddresses = fqdnAddresses;
    return this;
  }

  public SettingsDefaultProfile addFqdnAddressesItem(String fqdnAddressesItem) {
    if (this.fqdnAddresses == null) {
      this.fqdnAddresses = new ArrayList<>();
    }
    this.fqdnAddresses.add(fqdnAddressesItem);
    return this;
  }

   /**
   * Get fqdnAddresses
   * @return fqdnAddresses
  **/
  @ApiModelProperty(value = "")
  public List<String> getFqdnAddresses() {
    return fqdnAddresses;
  }

  public void setFqdnAddresses(List<String> fqdnAddresses) {
    this.fqdnAddresses = fqdnAddresses;
  }

  public SettingsDefaultProfile ipAddresses(List<String> ipAddresses) {
    this.ipAddresses = ipAddresses;
    return this;
  }

  public SettingsDefaultProfile addIpAddressesItem(String ipAddressesItem) {
    if (this.ipAddresses == null) {
      this.ipAddresses = new ArrayList<>();
    }
    this.ipAddresses.add(ipAddressesItem);
    return this;
  }

   /**
   * Get ipAddresses
   * @return ipAddresses
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpAddresses() {
    return ipAddresses;
  }

  public void setIpAddresses(List<String> ipAddresses) {
    this.ipAddresses = ipAddresses;
  }

  public SettingsDefaultProfile port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @ApiModelProperty(value = "")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public SettingsDefaultProfile proxy(Boolean proxy) {
    this.proxy = proxy;
    return this;
  }

   /**
   * Get proxy
   * @return proxy
  **/
  @ApiModelProperty(value = "")
  public Boolean isProxy() {
    return proxy;
  }

  public void setProxy(Boolean proxy) {
    this.proxy = proxy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingsDefaultProfile settingsDefaultProfile = (SettingsDefaultProfile) o;
    return Objects.equals(this.cert, settingsDefaultProfile.cert) &&
        Objects.equals(this.fqdnAddresses, settingsDefaultProfile.fqdnAddresses) &&
        Objects.equals(this.ipAddresses, settingsDefaultProfile.ipAddresses) &&
        Objects.equals(this.port, settingsDefaultProfile.port) &&
        Objects.equals(this.proxy, settingsDefaultProfile.proxy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cert, fqdnAddresses, ipAddresses, port, proxy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingsDefaultProfile {\n");
    
    sb.append("    cert: ").append(toIndentedString(cert)).append("\n");
    sb.append("    fqdnAddresses: ").append(toIndentedString(fqdnAddresses)).append("\n");
    sb.append("    ipAddresses: ").append(toIndentedString(ipAddresses)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

