/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import cisco.com.dnac.v1.api.client.model.DeviceInnerDeviceInfoAaaCredentials;
import cisco.com.dnac.v1.api.client.model.SettingsDefaultProfile;
import cisco.com.dnac.v1.api.client.model.SettingsSavaMappingList;
import cisco.com.dnac.v1.api.client.model.SettingsTaskTimeOuts;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Settings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class Settings {
  @SerializedName("_id")
  private String id = null;

  @SerializedName("aaaCredentials")
  private DeviceInnerDeviceInfoAaaCredentials aaaCredentials = null;

  @SerializedName("acceptEula")
  private Boolean acceptEula = null;

  @SerializedName("defaultProfile")
  private SettingsDefaultProfile defaultProfile = null;

  @SerializedName("savaMappingList")
  private List<SettingsSavaMappingList> savaMappingList = null;

  @SerializedName("taskTimeOuts")
  private SettingsTaskTimeOuts taskTimeOuts = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("version")
  private Integer version = null;

  public Settings id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Settings aaaCredentials(DeviceInnerDeviceInfoAaaCredentials aaaCredentials) {
    this.aaaCredentials = aaaCredentials;
    return this;
  }

   /**
   * Get aaaCredentials
   * @return aaaCredentials
  **/
  @ApiModelProperty(value = "")
  public DeviceInnerDeviceInfoAaaCredentials getAaaCredentials() {
    return aaaCredentials;
  }

  public void setAaaCredentials(DeviceInnerDeviceInfoAaaCredentials aaaCredentials) {
    this.aaaCredentials = aaaCredentials;
  }

  public Settings acceptEula(Boolean acceptEula) {
    this.acceptEula = acceptEula;
    return this;
  }

   /**
   * Get acceptEula
   * @return acceptEula
  **/
  @ApiModelProperty(value = "")
  public Boolean isAcceptEula() {
    return acceptEula;
  }

  public void setAcceptEula(Boolean acceptEula) {
    this.acceptEula = acceptEula;
  }

  public Settings defaultProfile(SettingsDefaultProfile defaultProfile) {
    this.defaultProfile = defaultProfile;
    return this;
  }

   /**
   * Get defaultProfile
   * @return defaultProfile
  **/
  @ApiModelProperty(value = "")
  public SettingsDefaultProfile getDefaultProfile() {
    return defaultProfile;
  }

  public void setDefaultProfile(SettingsDefaultProfile defaultProfile) {
    this.defaultProfile = defaultProfile;
  }

  public Settings savaMappingList(List<SettingsSavaMappingList> savaMappingList) {
    this.savaMappingList = savaMappingList;
    return this;
  }

  public Settings addSavaMappingListItem(SettingsSavaMappingList savaMappingListItem) {
    if (this.savaMappingList == null) {
      this.savaMappingList = new ArrayList<>();
    }
    this.savaMappingList.add(savaMappingListItem);
    return this;
  }

   /**
   * Get savaMappingList
   * @return savaMappingList
  **/
  @ApiModelProperty(value = "")
  public List<SettingsSavaMappingList> getSavaMappingList() {
    return savaMappingList;
  }

  public void setSavaMappingList(List<SettingsSavaMappingList> savaMappingList) {
    this.savaMappingList = savaMappingList;
  }

  public Settings taskTimeOuts(SettingsTaskTimeOuts taskTimeOuts) {
    this.taskTimeOuts = taskTimeOuts;
    return this;
  }

   /**
   * Get taskTimeOuts
   * @return taskTimeOuts
  **/
  @ApiModelProperty(value = "")
  public SettingsTaskTimeOuts getTaskTimeOuts() {
    return taskTimeOuts;
  }

  public void setTaskTimeOuts(SettingsTaskTimeOuts taskTimeOuts) {
    this.taskTimeOuts = taskTimeOuts;
  }

  public Settings tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public Settings version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.id, settings.id) &&
        Objects.equals(this.aaaCredentials, settings.aaaCredentials) &&
        Objects.equals(this.acceptEula, settings.acceptEula) &&
        Objects.equals(this.defaultProfile, settings.defaultProfile) &&
        Objects.equals(this.savaMappingList, settings.savaMappingList) &&
        Objects.equals(this.taskTimeOuts, settings.taskTimeOuts) &&
        Objects.equals(this.tenantId, settings.tenantId) &&
        Objects.equals(this.version, settings.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, aaaCredentials, acceptEula, defaultProfile, savaMappingList, taskTimeOuts, tenantId, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    aaaCredentials: ").append(toIndentedString(aaaCredentials)).append("\n");
    sb.append("    acceptEula: ").append(toIndentedString(acceptEula)).append("\n");
    sb.append("    defaultProfile: ").append(toIndentedString(defaultProfile)).append("\n");
    sb.append("    savaMappingList: ").append(toIndentedString(savaMappingList)).append("\n");
    sb.append("    taskTimeOuts: ").append(toIndentedString(taskTimeOuts)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

