/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SNMPvReadCommunityDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class SNMPvReadCommunityDTO {
  @SerializedName("comments")
  private String comments = null;

  /**
   * Gets or Sets credentialType
   */
  @JsonAdapter(CredentialTypeEnum.Adapter.class)
  public enum CredentialTypeEnum {
    GLOBAL("GLOBAL"),
    
    APP("APP");

    private String value;

    CredentialTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CredentialTypeEnum fromValue(String text) {
      for (CredentialTypeEnum b : CredentialTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CredentialTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CredentialTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CredentialTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CredentialTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("credentialType")
  private CredentialTypeEnum credentialType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("instanceTenantId")
  private String instanceTenantId = null;

  @SerializedName("instanceUuid")
  private String instanceUuid = null;

  @SerializedName("readCommunity")
  private String readCommunity = null;

  public SNMPvReadCommunityDTO comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public SNMPvReadCommunityDTO credentialType(CredentialTypeEnum credentialType) {
    this.credentialType = credentialType;
    return this;
  }

   /**
   * Get credentialType
   * @return credentialType
  **/
  @ApiModelProperty(value = "")
  public CredentialTypeEnum getCredentialType() {
    return credentialType;
  }

  public void setCredentialType(CredentialTypeEnum credentialType) {
    this.credentialType = credentialType;
  }

  public SNMPvReadCommunityDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SNMPvReadCommunityDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SNMPvReadCommunityDTO instanceTenantId(String instanceTenantId) {
    this.instanceTenantId = instanceTenantId;
    return this;
  }

   /**
   * Get instanceTenantId
   * @return instanceTenantId
  **/
  @ApiModelProperty(value = "")
  public String getInstanceTenantId() {
    return instanceTenantId;
  }

  public void setInstanceTenantId(String instanceTenantId) {
    this.instanceTenantId = instanceTenantId;
  }

  public SNMPvReadCommunityDTO instanceUuid(String instanceUuid) {
    this.instanceUuid = instanceUuid;
    return this;
  }

   /**
   * Get instanceUuid
   * @return instanceUuid
  **/
  @ApiModelProperty(value = "")
  public String getInstanceUuid() {
    return instanceUuid;
  }

  public void setInstanceUuid(String instanceUuid) {
    this.instanceUuid = instanceUuid;
  }

  public SNMPvReadCommunityDTO readCommunity(String readCommunity) {
    this.readCommunity = readCommunity;
    return this;
  }

   /**
   * Get readCommunity
   * @return readCommunity
  **/
  @ApiModelProperty(value = "")
  public String getReadCommunity() {
    return readCommunity;
  }

  public void setReadCommunity(String readCommunity) {
    this.readCommunity = readCommunity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SNMPvReadCommunityDTO snMPvReadCommunityDTO = (SNMPvReadCommunityDTO) o;
    return Objects.equals(this.comments, snMPvReadCommunityDTO.comments) &&
        Objects.equals(this.credentialType, snMPvReadCommunityDTO.credentialType) &&
        Objects.equals(this.description, snMPvReadCommunityDTO.description) &&
        Objects.equals(this.id, snMPvReadCommunityDTO.id) &&
        Objects.equals(this.instanceTenantId, snMPvReadCommunityDTO.instanceTenantId) &&
        Objects.equals(this.instanceUuid, snMPvReadCommunityDTO.instanceUuid) &&
        Objects.equals(this.readCommunity, snMPvReadCommunityDTO.readCommunity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comments, credentialType, description, id, instanceTenantId, instanceUuid, readCommunity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SNMPvReadCommunityDTO {\n");
    
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceTenantId: ").append(toIndentedString(instanceTenantId)).append("\n");
    sb.append("    instanceUuid: ").append(toIndentedString(instanceUuid)).append("\n");
    sb.append("    readCommunity: ").append(toIndentedString(readCommunity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

