/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TopologyResultResponseLinks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class TopologyResultResponseLinks {
  @SerializedName("additionalInfo")
  private Object additionalInfo = null;

  @SerializedName("endPortID")
  private String endPortID = null;

  @SerializedName("endPortIpv4Address")
  private String endPortIpv4Address = null;

  @SerializedName("endPortIpv4Mask")
  private String endPortIpv4Mask = null;

  @SerializedName("endPortName")
  private String endPortName = null;

  @SerializedName("endPortSpeed")
  private String endPortSpeed = null;

  @SerializedName("greyOut")
  private Boolean greyOut = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("linkStatus")
  private String linkStatus = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("startPortID")
  private String startPortID = null;

  @SerializedName("startPortIpv4Address")
  private String startPortIpv4Address = null;

  @SerializedName("startPortIpv4Mask")
  private String startPortIpv4Mask = null;

  @SerializedName("startPortName")
  private String startPortName = null;

  @SerializedName("startPortSpeed")
  private String startPortSpeed = null;

  @SerializedName("tag")
  private String tag = null;

  @SerializedName("target")
  private String target = null;

  public TopologyResultResponseLinks additionalInfo(Object additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Get additionalInfo
   * @return additionalInfo
  **/
  @ApiModelProperty(value = "")
  public Object getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(Object additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public TopologyResultResponseLinks endPortID(String endPortID) {
    this.endPortID = endPortID;
    return this;
  }

   /**
   * Get endPortID
   * @return endPortID
  **/
  @ApiModelProperty(value = "")
  public String getEndPortID() {
    return endPortID;
  }

  public void setEndPortID(String endPortID) {
    this.endPortID = endPortID;
  }

  public TopologyResultResponseLinks endPortIpv4Address(String endPortIpv4Address) {
    this.endPortIpv4Address = endPortIpv4Address;
    return this;
  }

   /**
   * Get endPortIpv4Address
   * @return endPortIpv4Address
  **/
  @ApiModelProperty(value = "")
  public String getEndPortIpv4Address() {
    return endPortIpv4Address;
  }

  public void setEndPortIpv4Address(String endPortIpv4Address) {
    this.endPortIpv4Address = endPortIpv4Address;
  }

  public TopologyResultResponseLinks endPortIpv4Mask(String endPortIpv4Mask) {
    this.endPortIpv4Mask = endPortIpv4Mask;
    return this;
  }

   /**
   * Get endPortIpv4Mask
   * @return endPortIpv4Mask
  **/
  @ApiModelProperty(value = "")
  public String getEndPortIpv4Mask() {
    return endPortIpv4Mask;
  }

  public void setEndPortIpv4Mask(String endPortIpv4Mask) {
    this.endPortIpv4Mask = endPortIpv4Mask;
  }

  public TopologyResultResponseLinks endPortName(String endPortName) {
    this.endPortName = endPortName;
    return this;
  }

   /**
   * Get endPortName
   * @return endPortName
  **/
  @ApiModelProperty(value = "")
  public String getEndPortName() {
    return endPortName;
  }

  public void setEndPortName(String endPortName) {
    this.endPortName = endPortName;
  }

  public TopologyResultResponseLinks endPortSpeed(String endPortSpeed) {
    this.endPortSpeed = endPortSpeed;
    return this;
  }

   /**
   * Get endPortSpeed
   * @return endPortSpeed
  **/
  @ApiModelProperty(value = "")
  public String getEndPortSpeed() {
    return endPortSpeed;
  }

  public void setEndPortSpeed(String endPortSpeed) {
    this.endPortSpeed = endPortSpeed;
  }

  public TopologyResultResponseLinks greyOut(Boolean greyOut) {
    this.greyOut = greyOut;
    return this;
  }

   /**
   * Get greyOut
   * @return greyOut
  **/
  @ApiModelProperty(value = "")
  public Boolean isGreyOut() {
    return greyOut;
  }

  public void setGreyOut(Boolean greyOut) {
    this.greyOut = greyOut;
  }

  public TopologyResultResponseLinks id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TopologyResultResponseLinks linkStatus(String linkStatus) {
    this.linkStatus = linkStatus;
    return this;
  }

   /**
   * Get linkStatus
   * @return linkStatus
  **/
  @ApiModelProperty(value = "")
  public String getLinkStatus() {
    return linkStatus;
  }

  public void setLinkStatus(String linkStatus) {
    this.linkStatus = linkStatus;
  }

  public TopologyResultResponseLinks source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public TopologyResultResponseLinks startPortID(String startPortID) {
    this.startPortID = startPortID;
    return this;
  }

   /**
   * Get startPortID
   * @return startPortID
  **/
  @ApiModelProperty(value = "")
  public String getStartPortID() {
    return startPortID;
  }

  public void setStartPortID(String startPortID) {
    this.startPortID = startPortID;
  }

  public TopologyResultResponseLinks startPortIpv4Address(String startPortIpv4Address) {
    this.startPortIpv4Address = startPortIpv4Address;
    return this;
  }

   /**
   * Get startPortIpv4Address
   * @return startPortIpv4Address
  **/
  @ApiModelProperty(value = "")
  public String getStartPortIpv4Address() {
    return startPortIpv4Address;
  }

  public void setStartPortIpv4Address(String startPortIpv4Address) {
    this.startPortIpv4Address = startPortIpv4Address;
  }

  public TopologyResultResponseLinks startPortIpv4Mask(String startPortIpv4Mask) {
    this.startPortIpv4Mask = startPortIpv4Mask;
    return this;
  }

   /**
   * Get startPortIpv4Mask
   * @return startPortIpv4Mask
  **/
  @ApiModelProperty(value = "")
  public String getStartPortIpv4Mask() {
    return startPortIpv4Mask;
  }

  public void setStartPortIpv4Mask(String startPortIpv4Mask) {
    this.startPortIpv4Mask = startPortIpv4Mask;
  }

  public TopologyResultResponseLinks startPortName(String startPortName) {
    this.startPortName = startPortName;
    return this;
  }

   /**
   * Get startPortName
   * @return startPortName
  **/
  @ApiModelProperty(value = "")
  public String getStartPortName() {
    return startPortName;
  }

  public void setStartPortName(String startPortName) {
    this.startPortName = startPortName;
  }

  public TopologyResultResponseLinks startPortSpeed(String startPortSpeed) {
    this.startPortSpeed = startPortSpeed;
    return this;
  }

   /**
   * Get startPortSpeed
   * @return startPortSpeed
  **/
  @ApiModelProperty(value = "")
  public String getStartPortSpeed() {
    return startPortSpeed;
  }

  public void setStartPortSpeed(String startPortSpeed) {
    this.startPortSpeed = startPortSpeed;
  }

  public TopologyResultResponseLinks tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public TopologyResultResponseLinks target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @ApiModelProperty(value = "")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopologyResultResponseLinks topologyResultResponseLinks = (TopologyResultResponseLinks) o;
    return Objects.equals(this.additionalInfo, topologyResultResponseLinks.additionalInfo) &&
        Objects.equals(this.endPortID, topologyResultResponseLinks.endPortID) &&
        Objects.equals(this.endPortIpv4Address, topologyResultResponseLinks.endPortIpv4Address) &&
        Objects.equals(this.endPortIpv4Mask, topologyResultResponseLinks.endPortIpv4Mask) &&
        Objects.equals(this.endPortName, topologyResultResponseLinks.endPortName) &&
        Objects.equals(this.endPortSpeed, topologyResultResponseLinks.endPortSpeed) &&
        Objects.equals(this.greyOut, topologyResultResponseLinks.greyOut) &&
        Objects.equals(this.id, topologyResultResponseLinks.id) &&
        Objects.equals(this.linkStatus, topologyResultResponseLinks.linkStatus) &&
        Objects.equals(this.source, topologyResultResponseLinks.source) &&
        Objects.equals(this.startPortID, topologyResultResponseLinks.startPortID) &&
        Objects.equals(this.startPortIpv4Address, topologyResultResponseLinks.startPortIpv4Address) &&
        Objects.equals(this.startPortIpv4Mask, topologyResultResponseLinks.startPortIpv4Mask) &&
        Objects.equals(this.startPortName, topologyResultResponseLinks.startPortName) &&
        Objects.equals(this.startPortSpeed, topologyResultResponseLinks.startPortSpeed) &&
        Objects.equals(this.tag, topologyResultResponseLinks.tag) &&
        Objects.equals(this.target, topologyResultResponseLinks.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalInfo, endPortID, endPortIpv4Address, endPortIpv4Mask, endPortName, endPortSpeed, greyOut, id, linkStatus, source, startPortID, startPortIpv4Address, startPortIpv4Mask, startPortName, startPortSpeed, tag, target);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopologyResultResponseLinks {\n");
    
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    endPortID: ").append(toIndentedString(endPortID)).append("\n");
    sb.append("    endPortIpv4Address: ").append(toIndentedString(endPortIpv4Address)).append("\n");
    sb.append("    endPortIpv4Mask: ").append(toIndentedString(endPortIpv4Mask)).append("\n");
    sb.append("    endPortName: ").append(toIndentedString(endPortName)).append("\n");
    sb.append("    endPortSpeed: ").append(toIndentedString(endPortSpeed)).append("\n");
    sb.append("    greyOut: ").append(toIndentedString(greyOut)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    linkStatus: ").append(toIndentedString(linkStatus)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    startPortID: ").append(toIndentedString(startPortID)).append("\n");
    sb.append("    startPortIpv4Address: ").append(toIndentedString(startPortIpv4Address)).append("\n");
    sb.append("    startPortIpv4Mask: ").append(toIndentedString(startPortIpv4Mask)).append("\n");
    sb.append("    startPortName: ").append(toIndentedString(startPortName)).append("\n");
    sb.append("    startPortSpeed: ").append(toIndentedString(startPortSpeed)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

