/*
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cisco.com.dnac.v1.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VlanListResultResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-06T09:46:49.053-05:00")
public class VlanListResultResponse {
  @SerializedName("interfaceName")
  private String interfaceName = null;

  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("mask")
  private Integer mask = null;

  @SerializedName("networkAddress")
  private String networkAddress = null;

  @SerializedName("numberOfIPs")
  private Integer numberOfIPs = null;

  @SerializedName("prefix")
  private String prefix = null;

  @SerializedName("vlanNumber")
  private Integer vlanNumber = null;

  @SerializedName("vlanType")
  private String vlanType = null;

  public VlanListResultResponse interfaceName(String interfaceName) {
    this.interfaceName = interfaceName;
    return this;
  }

   /**
   * Get interfaceName
   * @return interfaceName
  **/
  @ApiModelProperty(value = "")
  public String getInterfaceName() {
    return interfaceName;
  }

  public void setInterfaceName(String interfaceName) {
    this.interfaceName = interfaceName;
  }

  public VlanListResultResponse ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public VlanListResultResponse mask(Integer mask) {
    this.mask = mask;
    return this;
  }

   /**
   * Get mask
   * @return mask
  **/
  @ApiModelProperty(value = "")
  public Integer getMask() {
    return mask;
  }

  public void setMask(Integer mask) {
    this.mask = mask;
  }

  public VlanListResultResponse networkAddress(String networkAddress) {
    this.networkAddress = networkAddress;
    return this;
  }

   /**
   * Get networkAddress
   * @return networkAddress
  **/
  @ApiModelProperty(value = "")
  public String getNetworkAddress() {
    return networkAddress;
  }

  public void setNetworkAddress(String networkAddress) {
    this.networkAddress = networkAddress;
  }

  public VlanListResultResponse numberOfIPs(Integer numberOfIPs) {
    this.numberOfIPs = numberOfIPs;
    return this;
  }

   /**
   * Get numberOfIPs
   * @return numberOfIPs
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfIPs() {
    return numberOfIPs;
  }

  public void setNumberOfIPs(Integer numberOfIPs) {
    this.numberOfIPs = numberOfIPs;
  }

  public VlanListResultResponse prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @ApiModelProperty(value = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public VlanListResultResponse vlanNumber(Integer vlanNumber) {
    this.vlanNumber = vlanNumber;
    return this;
  }

   /**
   * Get vlanNumber
   * @return vlanNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getVlanNumber() {
    return vlanNumber;
  }

  public void setVlanNumber(Integer vlanNumber) {
    this.vlanNumber = vlanNumber;
  }

  public VlanListResultResponse vlanType(String vlanType) {
    this.vlanType = vlanType;
    return this;
  }

   /**
   * Get vlanType
   * @return vlanType
  **/
  @ApiModelProperty(value = "")
  public String getVlanType() {
    return vlanType;
  }

  public void setVlanType(String vlanType) {
    this.vlanType = vlanType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VlanListResultResponse vlanListResultResponse = (VlanListResultResponse) o;
    return Objects.equals(this.interfaceName, vlanListResultResponse.interfaceName) &&
        Objects.equals(this.ipAddress, vlanListResultResponse.ipAddress) &&
        Objects.equals(this.mask, vlanListResultResponse.mask) &&
        Objects.equals(this.networkAddress, vlanListResultResponse.networkAddress) &&
        Objects.equals(this.numberOfIPs, vlanListResultResponse.numberOfIPs) &&
        Objects.equals(this.prefix, vlanListResultResponse.prefix) &&
        Objects.equals(this.vlanNumber, vlanListResultResponse.vlanNumber) &&
        Objects.equals(this.vlanType, vlanListResultResponse.vlanType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interfaceName, ipAddress, mask, networkAddress, numberOfIPs, prefix, vlanNumber, vlanType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VlanListResultResponse {\n");
    
    sb.append("    interfaceName: ").append(toIndentedString(interfaceName)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    networkAddress: ").append(toIndentedString(networkAddress)).append("\n");
    sb.append("    numberOfIPs: ").append(toIndentedString(numberOfIPs)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    vlanNumber: ").append(toIndentedString(vlanNumber)).append("\n");
    sb.append("    vlanType: ").append(toIndentedString(vlanType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

